import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-[100dvh]">
          <Header />
          <main className="flex flex-col items-center justify-center flex-1 bg-gradient-to-br from-[#6B7280] to-[#374151] px-4 md:px-6 lg:px-8">
            <div className="max-w-md w-full space-y-8">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
